"""Create the frozen EPOS baseline schema.

Revision ID: 20260316_0002
Revises: 20260316_0001
Create Date: 2026-08-27 12:53:02.163479
"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel
from alembic import op
from sqlalchemy import inspect

revision: str = "20260316_0002"
down_revision: str | None = "20260316_0001"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    existing_tables = set(inspect(op.get_bind()).get_table_names()) - {"alembic_version"}
    if existing_tables:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "activity_events",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("occurred_at", sa.DateTime(), nullable=False),
        sa.Column("action", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("entity_type", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("entity_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("project_id", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("summary", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("detail", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("actor_email", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("actor_name", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("activity_events", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_activity_events_actor_email"), ["actor_email"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_activity_events_entity_id"), ["entity_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_activity_events_entity_type"), ["entity_type"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_activity_events_occurred_at"), ["occurred_at"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_activity_events_project_id"), ["project_id"], unique=False
        )

    op.create_table(
        "projects",
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("created_by", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("updated_by", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("deleted_at", sa.DateTime(), nullable=True),
        sa.Column("project_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("project_name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("domain", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("project_manager", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("start_date", sa.Date(), nullable=False),
        sa.Column("baseline_end_date", sa.Date(), nullable=True),
        sa.Column("forecast_end_date", sa.Date(), nullable=True),
        sa.Column("status_update_date", sa.Date(), nullable=True),
        sa.Column("project_phase", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("business_priority", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.PrimaryKeyConstraint("project_id"),
    )
    with op.batch_alter_table("projects", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_projects_deleted_at"), ["deleted_at"], unique=False)

    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("email", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("full_name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("password_hash", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column(
            "role",
            sa.Enum(
                "EXECUTIVE",
                "ENGINEER",
                "ENGINEERING_LEAD",
                "REQUIREMENTS_MANAGER",
                "PROJECT_MANAGER",
                "PMO_ANALYST",
                "ADMINISTRATOR",
                name="role",
            ),
            nullable=False,
        ),
        sa.Column("job_title", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("last_login_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_users_email"), ["email"], unique=True)

    op.create_table(
        "actions",
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("created_by", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("updated_by", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("deleted_at", sa.DateTime(), nullable=True),
        sa.Column("action_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("project_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("action_description", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("owner", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("due_date", sa.Date(), nullable=False),
        sa.Column("status", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("priority", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("source_reference", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.project_id"],
        ),
        sa.PrimaryKeyConstraint("action_id"),
    )
    with op.batch_alter_table("actions", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_actions_deleted_at"), ["deleted_at"], unique=False)
        batch_op.create_index(batch_op.f("ix_actions_project_id"), ["project_id"], unique=False)

    op.create_table(
        "change_requests",
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("created_by", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("updated_by", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("deleted_at", sa.DateTime(), nullable=True),
        sa.Column("change_request_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("project_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("requirement_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("change_description", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("reason", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("priority", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("status", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("requested_by", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("requested_date", sa.Date(), nullable=False),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.project_id"],
        ),
        sa.PrimaryKeyConstraint("change_request_id"),
    )
    with op.batch_alter_table("change_requests", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_change_requests_deleted_at"), ["deleted_at"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_change_requests_project_id"), ["project_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_change_requests_requirement_id"), ["requirement_id"], unique=False
        )

    op.create_table(
        "conversations",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("title", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("project_id", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("conversations", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_conversations_project_id"), ["project_id"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_conversations_user_id"), ["user_id"], unique=False)

    op.create_table(
        "decisions",
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("created_by", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("updated_by", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("deleted_at", sa.DateTime(), nullable=True),
        sa.Column("decision_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("project_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("title", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("description", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("category", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("decision_date", sa.Date(), nullable=False),
        sa.Column("owner", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("status", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("rationale", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("delivery_impact", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("related_milestone_id", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("related_risk_id", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("related_change_request_id", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("related_requirement_id", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("approver", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("approval_date", sa.Date(), nullable=True),
        sa.Column("notes", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.project_id"],
        ),
        sa.PrimaryKeyConstraint("decision_id"),
    )
    with op.batch_alter_table("decisions", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_decisions_deleted_at"), ["deleted_at"], unique=False)
        batch_op.create_index(batch_op.f("ix_decisions_project_id"), ["project_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_decisions_status"), ["status"], unique=False)

    op.create_table(
        "dependencies",
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("created_by", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("updated_by", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("deleted_at", sa.DateTime(), nullable=True),
        sa.Column("dependency_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("project_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("predecessor_type", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("predecessor_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("successor_type", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("successor_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("dependency_name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("status", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("delay_days", sa.Integer(), nullable=False),
        sa.Column("criticality", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.project_id"],
        ),
        sa.PrimaryKeyConstraint("dependency_id"),
    )
    with op.batch_alter_table("dependencies", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_dependencies_deleted_at"), ["deleted_at"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_dependencies_project_id"), ["project_id"], unique=False
        )

    op.create_table(
        "meeting_notes",
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("created_by", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("updated_by", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("deleted_at", sa.DateTime(), nullable=True),
        sa.Column("note_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("project_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("title", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("meeting_date", sa.Date(), nullable=False),
        sa.Column("attendees", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("body", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.project_id"],
        ),
        sa.PrimaryKeyConstraint("note_id"),
    )
    with op.batch_alter_table("meeting_notes", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_meeting_notes_deleted_at"), ["deleted_at"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_meeting_notes_project_id"), ["project_id"], unique=False
        )

    op.create_table(
        "milestones",
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("created_by", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("updated_by", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("deleted_at", sa.DateTime(), nullable=True),
        sa.Column("milestone_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("project_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("milestone_name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("baseline_date", sa.Date(), nullable=True),
        sa.Column("forecast_date", sa.Date(), nullable=True),
        sa.Column("status", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("criticality", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("owner", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.project_id"],
        ),
        sa.PrimaryKeyConstraint("milestone_id"),
    )
    with op.batch_alter_table("milestones", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_milestones_deleted_at"), ["deleted_at"], unique=False)
        batch_op.create_index(batch_op.f("ix_milestones_project_id"), ["project_id"], unique=False)

    op.create_table(
        "project_members",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("project_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("project_role", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.project_id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("project_members", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_project_members_project_id"), ["project_id"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_project_members_user_id"), ["user_id"], unique=False)

    op.create_table(
        "requirements",
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("created_by", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("updated_by", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("deleted_at", sa.DateTime(), nullable=True),
        sa.Column("requirement_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("project_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("requirement_text", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("requirement_type", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("priority", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("status", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("owner", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("last_updated_date", sa.Date(), nullable=True),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.project_id"],
        ),
        sa.PrimaryKeyConstraint("requirement_id"),
    )
    with op.batch_alter_table("requirements", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_requirements_deleted_at"), ["deleted_at"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_requirements_project_id"), ["project_id"], unique=False
        )

    op.create_table(
        "resources",
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("created_by", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("updated_by", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("deleted_at", sa.DateTime(), nullable=True),
        sa.Column("resource_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("resource_name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("project_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("allocated_hours", sa.Integer(), nullable=False),
        sa.Column("capacity_hours", sa.Integer(), nullable=False),
        sa.Column("week_start_date", sa.Date(), nullable=False),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.project_id"],
        ),
        sa.PrimaryKeyConstraint("resource_id"),
    )
    with op.batch_alter_table("resources", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_resources_deleted_at"), ["deleted_at"], unique=False)
        batch_op.create_index(batch_op.f("ix_resources_project_id"), ["project_id"], unique=False)

    op.create_table(
        "risks",
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("created_by", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("updated_by", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("deleted_at", sa.DateTime(), nullable=True),
        sa.Column("risk_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("project_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("risk_name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("probability", sa.Integer(), nullable=False),
        sa.Column("impact", sa.Integer(), nullable=False),
        sa.Column("status", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("mitigation_owner", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("mitigation_status", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("due_date", sa.Date(), nullable=False),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.project_id"],
        ),
        sa.PrimaryKeyConstraint("risk_id"),
    )
    with op.batch_alter_table("risks", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_risks_deleted_at"), ["deleted_at"], unique=False)
        batch_op.create_index(batch_op.f("ix_risks_project_id"), ["project_id"], unique=False)

    op.create_table(
        "saved_scenarios",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("dependency_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("additional_delay_days", sa.Integer(), nullable=False),
        sa.Column("as_of_date", sa.Date(), nullable=False),
        sa.Column("result_json", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("saved_scenarios", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_saved_scenarios_created_at"), ["created_at"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_saved_scenarios_dependency_id"), ["dependency_id"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_saved_scenarios_user_id"), ["user_id"], unique=False)

    op.create_table(
        "saved_views",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("surface", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("configuration_json", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("saved_views", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_saved_views_surface"), ["surface"], unique=False)
        batch_op.create_index(batch_op.f("ix_saved_views_user_id"), ["user_id"], unique=False)

    op.create_table(
        "tasks",
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("created_by", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("updated_by", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("deleted_at", sa.DateTime(), nullable=True),
        sa.Column("task_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("project_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("milestone_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("task_name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("owner", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("status", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("planned_end_date", sa.Date(), nullable=False),
        sa.Column("forecast_end_date", sa.Date(), nullable=False),
        sa.Column("completion_percent", sa.Integer(), nullable=False),
        sa.Column("is_blocked", sa.Boolean(), nullable=False),
        sa.Column("last_updated_date", sa.Date(), nullable=True),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.project_id"],
        ),
        sa.PrimaryKeyConstraint("task_id"),
    )
    with op.batch_alter_table("tasks", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_tasks_deleted_at"), ["deleted_at"], unique=False)
        batch_op.create_index(batch_op.f("ix_tasks_milestone_id"), ["milestone_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_tasks_project_id"), ["project_id"], unique=False)

    op.create_table(
        "test_cases",
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("created_by", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("updated_by", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("deleted_at", sa.DateTime(), nullable=True),
        sa.Column("test_case_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("project_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("test_case_name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("status", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("owner", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("verification_evidence", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("last_updated_date", sa.Date(), nullable=True),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.project_id"],
        ),
        sa.PrimaryKeyConstraint("test_case_id"),
    )
    with op.batch_alter_table("test_cases", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_test_cases_deleted_at"), ["deleted_at"], unique=False)
        batch_op.create_index(batch_op.f("ix_test_cases_project_id"), ["project_id"], unique=False)

    op.create_table(
        "trace_links",
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("created_by", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("updated_by", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("deleted_at", sa.DateTime(), nullable=True),
        sa.Column("trace_link_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("project_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("source_type", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("source_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("target_type", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("target_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("link_type", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.project_id"],
        ),
        sa.PrimaryKeyConstraint("trace_link_id"),
    )
    with op.batch_alter_table("trace_links", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_trace_links_deleted_at"), ["deleted_at"], unique=False)
        batch_op.create_index(batch_op.f("ix_trace_links_project_id"), ["project_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_trace_links_source_id"), ["source_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_trace_links_target_id"), ["target_id"], unique=False)

    op.create_table(
        "conversation_messages",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("conversation_id", sa.Integer(), nullable=False),
        sa.Column("role", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("content", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("matched_intent", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("status", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("source_ids_json", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("evidence_json", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["conversation_id"],
            ["conversations.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("conversation_messages", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_conversation_messages_conversation_id"),
            ["conversation_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_conversation_messages_created_at"), ["created_at"], unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    raise RuntimeError("The EPOS baseline migration cannot be downgraded destructively.")
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("conversation_messages", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_conversation_messages_created_at"))
        batch_op.drop_index(batch_op.f("ix_conversation_messages_conversation_id"))

    op.drop_table("conversation_messages")
    with op.batch_alter_table("trace_links", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_trace_links_target_id"))
        batch_op.drop_index(batch_op.f("ix_trace_links_source_id"))
        batch_op.drop_index(batch_op.f("ix_trace_links_project_id"))
        batch_op.drop_index(batch_op.f("ix_trace_links_deleted_at"))

    op.drop_table("trace_links")
    with op.batch_alter_table("test_cases", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_test_cases_project_id"))
        batch_op.drop_index(batch_op.f("ix_test_cases_deleted_at"))

    op.drop_table("test_cases")
    with op.batch_alter_table("tasks", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_tasks_project_id"))
        batch_op.drop_index(batch_op.f("ix_tasks_milestone_id"))
        batch_op.drop_index(batch_op.f("ix_tasks_deleted_at"))

    op.drop_table("tasks")
    with op.batch_alter_table("saved_views", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_saved_views_user_id"))
        batch_op.drop_index(batch_op.f("ix_saved_views_surface"))

    op.drop_table("saved_views")
    with op.batch_alter_table("saved_scenarios", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_saved_scenarios_user_id"))
        batch_op.drop_index(batch_op.f("ix_saved_scenarios_dependency_id"))
        batch_op.drop_index(batch_op.f("ix_saved_scenarios_created_at"))

    op.drop_table("saved_scenarios")
    with op.batch_alter_table("risks", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_risks_project_id"))
        batch_op.drop_index(batch_op.f("ix_risks_deleted_at"))

    op.drop_table("risks")
    with op.batch_alter_table("resources", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_resources_project_id"))
        batch_op.drop_index(batch_op.f("ix_resources_deleted_at"))

    op.drop_table("resources")
    with op.batch_alter_table("requirements", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_requirements_project_id"))
        batch_op.drop_index(batch_op.f("ix_requirements_deleted_at"))

    op.drop_table("requirements")
    with op.batch_alter_table("project_members", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_project_members_user_id"))
        batch_op.drop_index(batch_op.f("ix_project_members_project_id"))

    op.drop_table("project_members")
    with op.batch_alter_table("milestones", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_milestones_project_id"))
        batch_op.drop_index(batch_op.f("ix_milestones_deleted_at"))

    op.drop_table("milestones")
    with op.batch_alter_table("meeting_notes", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_meeting_notes_project_id"))
        batch_op.drop_index(batch_op.f("ix_meeting_notes_deleted_at"))

    op.drop_table("meeting_notes")
    with op.batch_alter_table("dependencies", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_dependencies_project_id"))
        batch_op.drop_index(batch_op.f("ix_dependencies_deleted_at"))

    op.drop_table("dependencies")
    with op.batch_alter_table("decisions", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_decisions_status"))
        batch_op.drop_index(batch_op.f("ix_decisions_project_id"))
        batch_op.drop_index(batch_op.f("ix_decisions_deleted_at"))

    op.drop_table("decisions")
    with op.batch_alter_table("conversations", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_conversations_user_id"))
        batch_op.drop_index(batch_op.f("ix_conversations_project_id"))

    op.drop_table("conversations")
    with op.batch_alter_table("change_requests", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_change_requests_requirement_id"))
        batch_op.drop_index(batch_op.f("ix_change_requests_project_id"))
        batch_op.drop_index(batch_op.f("ix_change_requests_deleted_at"))

    op.drop_table("change_requests")
    with op.batch_alter_table("actions", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_actions_project_id"))
        batch_op.drop_index(batch_op.f("ix_actions_deleted_at"))

    op.drop_table("actions")
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_users_email"))

    op.drop_table("users")
    with op.batch_alter_table("projects", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_projects_deleted_at"))

    op.drop_table("projects")
    with op.batch_alter_table("activity_events", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_activity_events_project_id"))
        batch_op.drop_index(batch_op.f("ix_activity_events_occurred_at"))
        batch_op.drop_index(batch_op.f("ix_activity_events_entity_type"))
        batch_op.drop_index(batch_op.f("ix_activity_events_entity_id"))
        batch_op.drop_index(batch_op.f("ix_activity_events_actor_email"))

    op.drop_table("activity_events")
    # ### end Alembic commands ###
